### ISSUE TITLE
Any plan for NS 7 compatibility

### ISSUE THREAD

**Issue by mdjamal** [liuy97/nativescript-soft-keyboard#4]
How to update plugins for NativeScript 7
https://nativescript.org/blog/nativescript-7-for-plugin-authors/

**Comment by liuy97** [comment]
Hi, I still use Nativescript 6.8. But I will upgrade this plugin soon.

**Comment by mdjamal** [comment]
Thanks @liuy97 look forward to it.

**Comment by liuy97** [comment]
@mdjamal , I have published nativescript-soft-keyboard v2.0.2 for NS 7.

**Comment by mdjamal** [comment]
@liuy97 thanks that was quick, and confirming that it works in NS7 and iOS 14.
