### ISSUE TITLE
Suggestion: update height to 0 when it closes

### ISSUE THREAD

**Issue by davecoffin** [liuy97/nativescript-soft-keyboard#6]
This is a helpful plugin, but it would be awesome if an event was thrown when the keyboard height changes to 0!

**Comment by liuy97** [comment]
All height changes will trigger SoftKeyboardCallback. You can check 0 height there. Does it not work for you?

**Comment by davecoffin** [comment]
No, dismissing the keyboard doesn’t trigger the height change event. I would think it should trigger a change event and the result be 0, but no event is fired.

**Comment by liuy97** [comment]
I cannot reproduce this bug. I confirmed I get 0-height in Android.

**Comment by davecoffin** [comment]
Issue is on iOS.

**Comment by oguzhanbolme** [comment]
@davecoffin how can i use detect to keyboard height ? It doesnt work for me. Which parameter should I put in it to make it work ?

**Comment by davecoffin** [comment]
@oguzhanbolme  Just follow the instructions: 
https://github.com/liuy97/nativescript-soft-keyboard/tree/master/packages/soft-keyboard
`registerSoftKeyboardCallback((h) => console.log(h))` h is the height.

**Comment by oguzhanbolme** [comment]
When clicking on the textfield, I want to print the keyboard height to the console, but it doesn't work. Also i am using the correct version
![kiko](https://user-images.githubusercontent.com/73880040/106758781-fb01b580-6642-11eb-87de-80147ae41c6c.png)

**Comment by achancu** [comment]
@davecoffin I've just created a PR that fixes this.

**Comment by davecoffin** [comment]
You rock!!

**Comment by achancu** [comment]
@davecoffin does it work for you?

**Comment by liuy97** [comment]
@achancu , thanks.
@davecoffin , I have confirmed that zero height is got. I add a sample in [demo-angular](https://github.com/liuy97/nativescript-soft-keyboard/tree/master/apps/demo-angular).
